### ISSUE TITLE
homebridge-beta: unhandled exception thrown by Ciao

### ISSUE THREAD

**Issue by adriancable** [homebridge/ciao#2]
Testing homebridge-beta. Ciao throws an unhandled exception if you run avahi-browse -at on the same device that is running homebridge.

[2296]: [6/13/2020, 11:00:47 AM] Error: Truncated messages are currently unsupported
[2296]:     at Responder.handleQuery (/root/node_modules/homebridge/node_modules/@homebridge/ciao/lib/Responder.js:232:19)
[2296]:     at MDNSServer.handleMessage (/root/node_modules/homebridge/node_modules/@homebridge/ciao/lib/MDNSServer.js:243:26)
[2296]:     at Socket.emit (events.js:315:20)
[2296]:     at UDP.onMessage (dgram.js:908:8)
[2296]: [6/13/2020, 11:00:47 AM] Got SIGTERM, shutting down Homebridge...

-Adrian

**Comment by Supereg** [comment]
Just never experienced this on my end, thus wasn't my highest priority at the time.

**Comment by adriancable** [comment]
Hi Andi - just to clarify, I know that Ciao is still under development and wasn't asking for support for specific things. But, it should not throw unhandled exceptions and crash Homebridge, so I think before it's supported just add a try/catch block to handle this and other unanticipated things.

-Adrian

**Comment by Supereg** [comment]
You are right, of course. This is something which slipped through from the early devs days.
Going to push an update soon, which will either just ignore such packets and print a warning or is adding support for truncated queries.

**Comment by adriancable** [comment]
@Supereg - that is awesome. Thank you!

**Comment by Supereg** [comment]
Took me a little more time than expected to get back working at this. Truncated queries, are now supported as of https://github.com/homebridge/ciao/commit/7247bd1c07a3fdec5a8ecb75a868ee6fac9a775c.
Will be part of the next beta dropping in the next few hours. Still want to ship some other improvements.

**Comment by adriancable** [comment]
@Supereg - that is awesome. I am very excited to see what you're doing with Homebridge right now - you've given it a new lease of life.

**Comment by Supereg** [comment]
alright, schedule didn't go as planned, got caught up rewriting the dns packet encoder/decoder 😅
Released a new beta 1.0.0-beta.17 which includes support for truncated queries. Anything else planned will be postponed to the next beta release.

**Comment by Supereg** [comment]
Forgot to mention, not releasing a new homebridge/hap-nodejs for this as reinstalling homebridge/hap-nodejs beta will just pull in the latest ciao version. So just reinstall homebrideg@beta and ciao will be updated to beta 17.

**Comment by adriancable** [comment]
Just tested the new Ciao and it works great with truncated queries. Great job! Apart from the usual regression testing, are there any reasons you can think of to still use bonjour-hap?

 

-Adrian

**Comment by Supereg** [comment]
> Apart from the usual regression testing, are there any reasons you can think of to still use bonjour-hap?

absolutely not. burry that thing 😅
well, ciao does not have a browser currently, so if you need that functionality, maybe. but the bonjour-hap browser is also broken (or rather not properly implemented) in so many ways.
