### ISSUE TITLE
npm update issues unsupported engine warning

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/ciao#30]
### Current Situation

performing an npm update command issues unsupported engine warning with CIAO v1.1.6 library

### Logs

```markdown
pi@nodejsdev:~$ npm update
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@homebridge/ciao@1.1.6',
npm WARN EBADENGINE   required: { node: '^14' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.5.1' }
npm WARN EBADENGINE }
```

### Configuration

```json
pi@nodejsdev:~$ npm list
pi@ /home/pi
├── axios@1.4.0
├── ffmpeg-for-homebridge@0.1.4
├── h264-sps-parser@0.2.1
├── hap-nodejs@0.11.1
├── pbf@3.2.1
├── rpio@2.4.2
└── ws@8.13.0
```

### Environment

- OS: Linux nodejsdev 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
- Software: HAP-NodeJS v0.11.1
- Node: v18.16.0
- npm: 9.5.1

### Process Supervisor

not applicable

**Comment by pgerke** [comment]
Looking at the changes between v1.1.5 and v1.1.6, especially https://github.com/homebridge/ciao/compare/v1.1.5...v1.1.6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R73-R75 I could imagine a typo. I'd expect the intent was not to limit engines to Node 14, but to a node version larger than or equal to Node 14:

```json
{
  ...
  "engines": {
    "node": ">=14"
  }
}
```
