### ISSUE TITLE
arp command don't exist on some distribution

### ISSUE THREAD

**Issue by NebzHB** [homebridge/ciao#4]
Dears,

arp command (net-tools) don't exists anymore on some distribution, could you check and adapt with `ip n` ?

2020-09-15T07:05:53.881Z ciao:NetworkManager WARNING Detecting network interfaces for platform 'linux' failed. Trying to assume network interfaces! (Command failed: arp -n -a | grep -v incomplete
/bin/sh: 1: arp: not found
)

**Comment by Supereg** [comment]
On those distros where arp is missing, the ip command will most likely miss too.
1.2.1 though did. already fix that with an workaround. The message will still display though, but in the background it will automatically switch to the fallback method.

**Comment by NebzHB** [comment]
could you please avoid the message ?

if i'm not wrong, net-tools are not in debian netinst by default...

**Comment by Supereg** [comment]
will be silenced in the next release
